# Generated by Django 4.1.2 on 2022-10-24 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rpg', '0004_qpsettingsrpg_limit_characters'),
    ]

    operations = [
        migrations.CreateModel(
            name='qpCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Last Name')),
                ('resistance_physical', models.PositiveSmallIntegerField(default=0, verbose_name='Physique Resistance')),
                ('resistance_mental', models.PositiveSmallIntegerField(default=0, verbose_name='Mental Resistance')),
                ('resistance_spiritual', models.PositiveSmallIntegerField(default=0, verbose_name='Spiritual Resistance')),
                ('attribute_strength', models.PositiveSmallIntegerField(default=0, verbose_name='Strength')),
                ('attribute_constitution', models.PositiveSmallIntegerField(default=0, verbose_name='Constitution')),
                ('attribute_dexterity', models.PositiveSmallIntegerField(default=0, verbose_name='Dexterity')),
                ('attribute_perception', models.PositiveSmallIntegerField(default=0, verbose_name='Perception')),
                ('attribute_intelligence', models.PositiveSmallIntegerField(default=0, verbose_name='Intelligence')),
                ('attribute_willpower', models.PositiveSmallIntegerField(default=0, verbose_name='Willpower')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('rpg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='rpg.qprpg', verbose_name='RPG')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'ordering': ['last_name', 'middle_name', 'first_name'],
            },
        ),
    ]
