# Generated by Django 4.1.2 on 2022-10-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_qpcharacter_resistance_physical'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpcharacter',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='characters/avatars', verbose_name='Avatar'),
        ),
    ]
