# Generated by Django 4.1.2 on 2022-10-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_qpcharacter_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpcharacter',
            name='gender',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('male', 'Male'), ('female', 'Female')], default='unknown', max_length=32, verbose_name='Gender'),
        ),
    ]
