# Generated by Django 4.1.2 on 2022-10-30 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
        ('characters', '0005_qpcharacter_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpcharacter',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='forums.qpforumsection', verbose_name='Location'),
        ),
    ]
