# Generated by Django 4.1.2 on 2022-10-30 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0006_qprpgrace_name_female_qprpgrace_name_male'),
        ('characters', '0006_qpcharacter_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='qpCharacterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.PositiveBigIntegerField(default=0, verbose_name='Experience')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='characters.qpcharacter', verbose_name='Character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='rpg.qprpgskill', verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['skill'],
            },
        ),
    ]
