# Generated by Django 4.1.2 on 2022-10-30 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0010_qpsettingsrpg_limit_inventory_size_character_and_more'),
        ('characters', '0007_qpcharacterskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='qpCharacterCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='characters.qpcharacter', verbose_name='Character')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters_currencies', to='rpg.qprpgcurrency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['character', 'currency'],
            },
        ),
    ]
