# Generated by Django 4.1.2 on 2022-10-30 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_qpcharactercurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpcharactercurrency',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='characters.qpcharacter', verbose_name='Character'),
        ),
    ]
