# Generated by Django 4.1.2 on 2022-10-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_remove_qpcharactercurrency_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpcharactercurrency',
            name='amount_max',
        ),
        migrations.RemoveField(
            model_name='qpcharactercurrency',
            name='amount_min',
        ),
        migrations.AddField(
            model_name='qpcharactercurrency',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Amount'),
        ),
    ]
