# Generated by Django 4.1.2 on 2022-10-19 14:30

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='qpUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='name', unique=True, verbose_name='Slug')),
                ('lang', models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='fr', max_length=6, verbose_name='Language')),
                ('timezone', models.CharField(choices=[('America/Toronto', 'America/Toronto'), ('Europe/Paris', 'Europe/Paris')], default='America/Toronto', max_length=32, verbose_name='Timezone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars', verbose_name='Avatar')),
                ('limit_max_projects', models.PositiveSmallIntegerField(default=2, verbose_name='Max Projects')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
