# Generated by Django 4.1.1 on 2022-10-09 16:33

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_qpuserprofile_options_alter_qpuserprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpuserprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='name', unique=True, verbose_name='Slug'),
        ),
    ]
