# Generated by Django 4.1.1 on 2022-10-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_qpuserprofile_limit_max_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpuserprofile',
            name='lang',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='fr', max_length=6, verbose_name='Language'),
        ),
    ]
