# Generated by Django 4.1.1 on 2022-10-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_qpuserprofile_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpuserprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars', verbose_name='Avatar'),
        ),
    ]
