# Generated by Django 4.1.1 on 2022-10-10 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_qpproject_options_alter_qpproject_created_at_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpnotification',
            name='project_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_from', to='projects.qpproject', verbose_name='From Project'),
        ),
    ]
