# Generated by Django 4.1.1 on 2022-10-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_qpnotification_project_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qpnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
