# Generated by Django 4.1.2 on 2022-10-29 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0002_alter_qpcharacter_resistance_physical'),
        ('forums', '0001_initial'),
        ('rpg', '0005_alter_qprpgskill_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='qpQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='Level')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('rpg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='rpg.qprpg')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='forums.qpforumsection')),
                ('skills', models.ManyToManyField(related_name='quests', to='rpg.qprpgskill', verbose_name='Skills')),
            ],
            options={
                'verbose_name': 'Quest',
                'verbose_name_plural': 'Quests',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='qpQuestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Start at')),
                ('end', models.DateTimeField(verbose_name='End at')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('is_success', models.BooleanField(default=False, verbose_name='Success')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questlogs', to='characters.qpcharacter', verbose_name='Character')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='quests.qpquest', verbose_name='Quest')),
            ],
            options={
                'verbose_name': 'Quest Log',
                'verbose_name_plural': 'Quest Logs',
                'ordering': ['-updated_at'],
            },
        ),
    ]
