# Generated by Django 4.1.2 on 2022-10-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0003_qpquestlog_reward_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpquestlog',
            name='reward_exp',
        ),
        migrations.AddField(
            model_name='qpquest',
            name='reward_exp',
            field=models.PositiveIntegerField(default=1, verbose_name='Reward Experience'),
        ),
    ]
