# Generated by Django 4.1.2 on 2022-10-30 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0010_qpsettingsrpg_limit_inventory_size_character_and_more'),
        ('quests', '0005_qpquest_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='qpQuestRewardCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_reward_currencies', to='rpg.qprpgcurrency', verbose_name='Currency')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_currencies', to='quests.qpquest', verbose_name='Quest')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['quest', 'currency'],
            },
        ),
    ]
