# Generated by Django 4.1.1 on 2022-10-09 16:34

import autoslug.fields
import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='qpProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='name', unique=True, verbose_name='Slug')),
                ('caption', models.CharField(blank=True, max_length=120, null=True, verbose_name='Caption')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('primary_color', colorfield.fields.ColorField(default='#89a411', image_field=None, max_length=18, samples=None, verbose_name='Primary Colour')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='projects/icons', verbose_name='Icon')),
                ('is_public', models.BooleanField(default=True, help_text='Designates whether this project should be visible for everyone. Unselect this to make it visible only for staff.', verbose_name='Public')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this project should be treated as active. Unselect this instead of deleting project.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
