# Generated by Django 4.1.1 on 2022-10-17 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_alter_qpproject_options_alter_qpproject_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpproject',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Score'),
        ),
        migrations.CreateModel(
            name='qpProjectPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_task', models.BooleanField(default=False, verbose_name='Create Task')),
                ('can_edit_task', models.BooleanField(default=False, verbose_name='Edit Task')),
                ('can_delete_task', models.BooleanField(default=False, verbose_name='Delete Task')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='projects.qpproject', verbose_name='Permissions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_permissions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Permissions',
                'verbose_name_plural': 'Permissions',
                'ordering': ['project'],
            },
        ),
    ]
