# Generated by Django 4.1.2 on 2022-10-31 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0010_qpsettingsrpg_limit_inventory_size_character_and_more'),
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qpforum',
            options={'ordering': ['rpg__name'], 'verbose_name': 'Forum', 'verbose_name_plural': 'Forums'},
        ),
        migrations.RemoveField(
            model_name='qpforum',
            name='name',
        ),
        migrations.RemoveField(
            model_name='qpforum',
            name='slug',
        ),
        migrations.AddField(
            model_name='qpforum',
            name='rpg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rpg', to='rpg.qprpg'),
            preserve_default=False,
        ),
    ]
