# Generated by Django 4.1.2 on 2022-10-19 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0002_alter_qpforumcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qpforumcategory',
            options={'ordering': ['forum', 'order'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='qpforumsection',
            options={'ordering': ['category', 'order'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AddField(
            model_name='qpforumtopic',
            name='flag',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Normal'), (1, 'Helpful'), (2, 'Important'), (3, 'Mandatory')], default=0, verbose_name='Flag'),
        ),
        migrations.CreateModel(
            name='qpForumTrackTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='forums.qpforumtopic', verbose_name='Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_tracks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='qpForumTrackSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='forums.qpforumsection', verbose_name='Section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_tracks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
