# Generated by Django 4.1.2 on 2022-10-31 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0010_qpsettingsrpg_limit_inventory_size_character_and_more'),
        ('forums', '0002_alter_qpforum_options_remove_qpforum_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpforum',
            name='rpg',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rpg', to='rpg.qprpg'),
        ),
    ]
