# Generated by Django 4.1.2 on 2022-10-31 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_alter_qpforumtopic_options_alter_qpforum_rpg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpforum',
            name='owner',
        ),
    ]
