# Generated by Django 4.1.2 on 2022-10-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_remove_qpforum_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpforumcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='qpforumsection',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='qpforumsection',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(24, '100%'), (18, '75%'), (16, '66%'), (12, '50%'), (8, '33%'), (6, '25%')], default=24, null=True, verbose_name='Width'),
        ),
    ]
