# Generated by Django 4.1.2 on 2022-10-24 18:39

import autoslug.fields
import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='qpRpg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='name', unique=True, verbose_name='Slug')),
                ('caption', models.CharField(blank=True, max_length=120, null=True, verbose_name='Caption')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('primary_color', colorfield.fields.ColorField(default='#89a411', image_field=None, max_length=18, samples=None, verbose_name='Primary Colour')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='rpgs/icons', verbose_name='Icon')),
                ('is_public', models.BooleanField(default=True, help_text='Designates whether this RPG should be visible for everyone. Unselect this to make it visible only for staff.', verbose_name='Public')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this RPG should be treated as active. Unselect this instead of deleting RPG.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rpgs', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_rpgs', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'RPG',
                'verbose_name_plural': 'RPGs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='qpSettingsRpg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier_resistance_physical', models.SmallIntegerField(default=0, verbose_name='Physical Resistance Modifier')),
                ('modifier_resistance_mental', models.SmallIntegerField(default=0, verbose_name='Mental Resistance Modifier')),
                ('modifier_resistance_spiritual', models.SmallIntegerField(default=0, verbose_name='Spiritual Resistance Modifier')),
                ('rpg', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='rpg.qprpg')),
            ],
            options={
                'verbose_name': 'RPG Setting',
                'verbose_name_plural': 'RPG Settings',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='qpRpgSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('attribute', models.CharField(choices=[('strength', 'Strength'), ('constitution', 'Constitution'), ('dexterity', 'Dexterity'), ('perception', 'Perception'), ('intelligence', 'Intelligence'), ('willpower', 'Volonté')], max_length=32, verbose_name='Attribute')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('rpg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='rpg.qprpg')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='qpRpgRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('rpg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='rpg.qprpg')),
            ],
            options={
                'verbose_name': 'Race',
                'verbose_name_plural': 'Races',
                'ordering': ['name'],
            },
        ),
    ]
