# Generated by Django 4.1.2 on 2022-10-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='qpRpgSkills',
            new_name='qpRpgSkill',
        ),
    ]
