# Generated by Django 4.1.2 on 2022-10-24 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rpg', '0002_rename_qprpgskills_qprpgskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpsettingsrpg',
            name='limit_races',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Races Limit'),
        ),
        migrations.AddField(
            model_name='qpsettingsrpg',
            name='limit_skills',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Skills Limit'),
        ),
        migrations.AlterField(
            model_name='qprpg',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rpg', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='qprpg',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_rpg', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
