# Generated by Django 4.1.2 on 2022-10-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0003_qpsettingsrpg_limit_races_qpsettingsrpg_limit_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpsettingsrpg',
            name='limit_characters',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Characters Limit'),
        ),
    ]
