# Generated by Django 4.1.2 on 2022-10-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0004_qpsettingsrpg_limit_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qprpgskill',
            name='attribute',
            field=models.CharField(choices=[('strength', 'Strength'), ('constitution', 'Constitution'), ('dexterity', 'Dexterity'), ('perception', 'Perception'), ('intelligence', 'Intelligence'), ('willpower', 'Willpower')], max_length=32, verbose_name='Attribute'),
        ),
    ]
