# Generated by Django 4.1.2 on 2022-10-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0005_alter_qprpgskill_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='qprpgrace',
            name='name_female',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Female Name'),
        ),
        migrations.AddField(
            model_name='qprpgrace',
            name='name_male',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Male Name'),
        ),
    ]
