# Generated by Django 4.1.2 on 2022-10-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0006_qprpgrace_name_female_qprpgrace_name_male'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpsettingsrpg',
            name='quest_malus_level_difference',
            field=models.FloatField(default=0.25, verbose_name='Malus of Quest Level Difference'),
        ),
    ]
