# Generated by Django 4.1.2 on 2022-10-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0008_qpsettingsrpg_total_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpsettingsrpg',
            name='quest_modifier_destiny',
            field=models.FloatField(default=0.05, verbose_name='Modifier of Quest Destiny'),
        ),
    ]
