# Generated by Django 4.1.2 on 2022-10-30 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0009_qpsettingsrpg_quest_modifier_destiny'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpsettingsrpg',
            name='limit_inventory_size_character',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Character Inventory Size Limit'),
        ),
        migrations.CreateModel(
            name='qpRpgCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('icon', models.CharField(default='mdi mdi-cash-multiple', max_length=120, verbose_name='Icon')),
                ('rpg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='rpg.qprpg')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['rpg', 'order'],
            },
        ),
    ]
