# Generated by Django 4.1.2 on 2022-11-01 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0010_qpsettingsrpg_limit_inventory_size_character_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='qpRpgStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('stylesheet', models.TextField(blank=True, null=True, verbose_name='Stylesheet')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('rpg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style', to='rpg.qprpg', verbose_name='RPG')),
            ],
            options={
                'verbose_name': 'Style',
                'verbose_name_plural': 'Styles',
                'ordering': ['rpg', 'name'],
            },
        ),
    ]
