name: Move assigned card
on:
  issues:
    types:
      - created
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: @mcpronovost/oykus
          column: Todo
          repo-token: ${{ secrets.MY_GITHUB_TOKEN }}
