name: Move When Labelled

on:
  issues:
    types:
      - labeled

jobs:
  add-to-project:
    name: Move issue when labelled
    runs-on: ubuntu-latest
    steps:

      - uses: titoportas/update-project-fields@v0.1.0
        id: inProgressItem
        if: |
          contains(github.event.issue.labels.*.name, 'In Progress')
        with:
          project-url: https://github.com/users/mcpronovost/projects/2
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          item-id: ${{ steps.inProgressItem.outputs.itemId }}
          field-keys: Status
          field-values: "In Progress"

      - uses: titoportas/update-project-fields@v0.1.0
        id: inFeatureItem
        if: |
          contains(github.event.issue.labels.*.name, 'Feature for future')
        with:
          project-url: https://github.com/users/mcpronovost/projects/2
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          item-id: ${{ steps.inFeatureItem.outputs.itemId }}
          field-keys: Status
          field-values: "In Development"