name: Move When Labelled

on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: mishraprafful/Github-Board-Actions@master
      with:
        action-token: "${{ secrets.MY_GITHUB_TOKEN }}"
        project-url: "https://github.com/mcpronovost/qp-oykus/projects/2"
        column-name: "In Progress"
        label-name: "In Progress"
        columns-to-ignore: "Done"
    - uses: mishraprafful/Github-Board-Actions@master
      with:
        action-token: "${{ secrets.MY_GITHUB_TOKEN }}"
        project-url: "https://github.com/mcpronovost/qp-oykus/projects/2"
        column-name: "In Development"
        label-name: "Feature for future"
        columns-to-ignore: "Done"
