name: Move In Progress

on:
  issues:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        id: addItem
        with:
          project-url: https://github.com/users/mcpronovost/projects/2
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          labeled: "In Progress"

      - uses: kalgurn/update-project-item-status@main
        with:
          project-url: https://github.com/users/mcpronovost/projects/2
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          item-id: ${{ steps.addItem.outputs.itemId }}
          status: "In Progress"