name: Move When Labelled

on:
  issues:
    types: [labeled]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Move When Labelled
    steps:

    - name: Assign issues requests with `In Progress` label
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'In Progress')
      with:
        project: 'https://github.com/users/mcpronovost/projects/2'
        column_name: 'In Progress'