name: Move issue labeled as "In Progress"

on:
  issues:
    types: [labeled]

jobs:
  move-in-progress:
    runs-on: ubuntu-latest
    steps:
    - name: Move labeled issue
      uses: alxarno/move-labeled-or-milestoned-issue@5.7
      with:
        action-token: "${{ secrets.MY_GITHUB_TOKEN }}"
        project-url: "https://github.com/mcpronovost/projects/2"
        column-name: "In Progress"
        label-name: "In Progress"
